#! /usr/bin/env bash

xrandr --output DVI-I-1-1 --auto --right-of DVI-I-2-2
xrandr --output DVI-I-2-2 --auto --primary --left-of DVI-I-1-1

MONITORS=$(xrandr --listactivemonitors | grep Monitors | tr -dc '0-9')

if [ $MONITORS -gt 1 ]; then
    xrandr --output eDP --off
else
    xrandr --output eDP --auto --below DVI-I-2-2
fi

